version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - KTOR_DEVELOPMENT=true
      - LOOKUP_API_KEY=some_key
      - AUTH_USER=admin
      - AUTH_PASSWORD=admin
    volumes:
      - .:/app
