version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: csgo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8085:8085"
    environment:
      DB_URL: jdbc:postgresql://db:5432/csgo
      DB_USER: postgres
      DB_PASSWORD: 1234
      KTOR_DEVELOPMENT: true
      LOOKUP_API_KEY: some_key
      AUTH_USER: admin
      AUTH_PASSWORD: admin
      IMPORT_DATA_ONCE: "true"

volumes:
  pgdata:
